import React from 'react';
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

function Index(props) {
    return (
        <>
            <Head>
                <title>SGME - Sobre</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className="container">
                <section className="container">
                    <div
                        className="d-sm-flex flex-md-row-reverse mb-2 mt-5 align-items-center"
                    >
                        <div className="d-sm-flex p-2">
                            <Image src="/img/img_info.svg" width={350} height={350} alt="" />
                        </div>

                        <div
                            className="d-sm-flex flex-sm-column p-2 justify-content-between"
                        >
                            <h2 className="mb-5 ">
                                UM SISTEMA PENSADO PARA O MICROEMPREENDEDOR
                            </h2>
                            <p className="fs-5">
                                A <span className="text-paleta_blue"><strong>SGME</strong> </span> é
                                uma plataforma onde o microempreendedor terá a oportunidade de
                                aprender a fazer a gestão do seu negócio e ter acesso a
                                conhecimentos que o ajudarão nessa missão.
                            </p>
                            <p className="fs-5">Além de uma plataforma
                                de gestao de negócios de forma simplificada, para garantir uma
                                usabilidade de facil aprendezido e utilizaçao. Contando desde
                                gestão de vendas até gestão de contas a pagar e a receber.</p>
                            <Link href="#" className="btn btn-warning fs-4 w-100"
                            >Cadastre-se gratuitamente aqui!</Link
                            >
                        </div>
                    </div>
                </section>

                <section className="container-sm" >
                    <div className="p-2 d-sm-flex align-items-center">
                        <div className="me-4">
                            <Image src="/img/icone_missao.svg" width={300} height={300} alt="" />
                        </div>

                        <div className="pe-2">
                            <h1 className="mb-4">Missão</h1>
                            {/* eslint-disable-next-line react/no-unescaped-entities */}
                            <p className="fs-4">"Fomentar a capacitaçao de micro e pequenos empreendedores, fornecendo uma orientação educacional sólida e ferramentas para facilitar a gestão completa do seu negócio, guiando-os rumo ao sucesso."</p>
                        </div>
                    </div>

                    <div className="container-sm p-2 d-sm-flex flex-md-row-reverse align-items-center">
                        <div className="container_content missao_img w-25 me-5">
                            <Image src="/img/icone_visao.svg" height={300} width={300} alt="" />
                        </div>

                        <div
                            className="pe-2 d-sm-flex flex-md-column justify-content-between"
                        >
                            <h1 className="mb-4">Visão</h1>
                            <p className="fs-4">"Nós tornarmos a maior referência e fonte de inspiração para empreendedores
                                iniciantes, sendo reconhecido como um parceiro de plena confiança e ferramenta fundamental
                                para alcançar o ápice."
                            </p>
                        </div>
                    </div>

                    <div className="Valores p-2 d-lg-flex align-items-center">

                        <div className="container-sm">
                            <Image src="/img/icone_valores.svg"  width={300} height={300} alt="" />
                        </div>

                        <div className="ms-3 pe-2">
                            <h1 className="mb-4">Valores</h1>
                            <p className="fs-4">
                                "Comprometimento com o aprendizado, orientação e apoio aos micro e
                                pequenos empreendedores, impulsionando-os a obter total controle e
                                crescimento continuo do seu negócio."
                            </p>
                        </div>

                    </div>

                </section>



            </main>
        </>
    );
}

export default Index;