import React from 'react';
import Image from "next/image";
import Head from "next/head";

function Index(props) {
    return (
        <>
            <Head>
                <title>SGME - Funcionalidades</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>

            </Head>

            <main className="container">

            <div className="w-100 d-sm-flex  align-items-center">
                <h1 className="fs-1 p-2 me-4">
                    O <span className="text-warning fw-bold">SGME</span>  é o sistema perfeito para te auxiliar na gestão do seu negócio.
                </h1>

                <div className="banner_img">
                    <Image src="/img/img_banner_funcionalidades.svg" width={400} height={400} className="img-sgme w-100" alt="" />
                </div>
            </div>


            <div className="container">
                <h1 className="fs-2 text-center mb-5">
                    <span className="text-paleta_blue">Conheça</span> tudo o que oferecemos!
                </h1>

                <div className="accordion" id="accordionExample">
                    <div className="accordion-item">
                        <h2 className="accordion-header">
                            <button className="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne"
                                    aria-expanded="true" aria-controls="collapseOne">
                                PDV - Ponto de Venda
                            </button>
                        </h2>
                        <div id="collapseOne" className="accordion-collapse collapse show" data-bs-parent="#accordionExample">
                            <div className="accordion-body">
                                <p>
                                    Frente de Caixa (PDV): Controle suas vendas com praticidade.
                                    O sistema <span className="text-danger">SGME</span> possui a
                                    ferramenta para você gerenciar seu ponto de venda com o
                                    máximo de agilidade e eficiência. Integrações de seu estoque
                                    físico com sua loja virtual e marketplaces, automatizações
                                    na leitura de códigos de barras, entre outras vantagens.
                                </p>

                                <div className="item-accordion w-100 d-flex justify-content-end">
                                    <a href="#" className="btn btn-warning"> Saiba Mais!</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="accordion-item">
                        <h2 className="accordion-header">
                            <button className="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                    data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                Movimentação de Estoque.
                            </button>
                        </h2>
                        <div id="collapseTwo" className="accordion-collapse collapse" data-bs-parent="#accordionExample">
                            <div className="accordion-body">
                                <p>
                                    Com o sistema de SGME, você faz o controle de estoque de
                                    seus produtos, peças e insumos de forma simples, evitando
                                    erros nos processos. Garanta o total controle de vendas de
                                    seu negócio, enviando ordens de compra para fornecedores,
                                    gerenciando múltiplos depósitos e muito mais.
                                </p>

                                <div className="item-accordion w-100 d-flex justify-content-end">
                                    <a href="#" className="btn btn-warning"> Saiba Mais!</a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div className="accordion-item">
                        <h2 className="accordion-header">
                            <button className="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                    data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                Cadastros
                            </button>
                        </h2>
                        <div id="collapseThree" className="accordion-collapse collapse" data-bs-parent="#accordionExample">
                            <div className="accordion-body">
                                <p>
                                    <strong>Cadastre seus produtos, fornecedores, categorias e clientes</strong> para ter controle de
                                    estoque, cadatrar suas contas a pagar e receber, e conhecer quem são seus clientes.
                                </p>
                            </div>

                            <div className="item-accordion w-100 d-flex justify-content-end">
                                <a href="#" className="btn btn-warning"> Saiba Mais!</a>
                            </div>
                        </div>
                    </div>

                    <div className="accordion-item">
                        <h2 className="accordion-header">
                            <button className="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                    data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                                Gestão Financeira
                            </button>
                        </h2>
                        <div id="collapseFour" className="accordion-collapse collapse" data-bs-parent="#accordionExample">
                            <div className="accordion-body">
                                <strong>Tenha na palma da sua mão tudo sobre a saúde financeira do seu negócio.</strong> Não sofra mais
                                com perdas por pagamentos de juros ou por não receber do seu cliente no dia certo e não saber quanto
                                tem para receber. Tenha também informações sobre suas vendas, fluxo de capital e controle de custos;
                            </div>

                            <div className="item-accordion w-100 d-flex justify-content-end">
                                <a href="#" className="btn btn-warning"> Saiba Mais!</a>
                            </div>
                        </div>
                    </div>

                    <div className="accordion-item">
                        <h2 className="accordion-header">
                            <button className="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                    data-bs-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
                                Relatórios
                            </button>
                        </h2>
                        <div id="collapseFive" className="accordion-collapse collapse" data-bs-parent="#accordionExample">
                            <div className="accordion-body">
                                <strong>Use e abuse dos relatorios disponíveis para ficar por dentro de tudo que acontece no seu
                                    negócio.</strong> Sempre tendo em mãos o valor de suas vendas, despesas e valores a receber e a pagar,
                                evitando perdas.
                            </div>
                            <div className="item-accordion w-100 d-flex justify-content-end">
                                <a href="#" className="btn btn-warning"> Saiba Mais!</a>
                            </div>
                        </div>
                    </div>

                    <div className="accordion-item">
                        <h2 className="accordion-header">
                            <button className="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                    data-bs-target="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
                                Base de Conhecimentos
                            </button>
                        </h2>
                        <div id="collapseSix" className="accordion-collapse collapse" data-bs-parent="#accordionExample">
                            <div className="accordion-body">
                                <strong>Aprenda a gerir o seu negocio</strong> Com nossa base de conhecimento você tem acesso as melhores
                                informações para fazer a gestão do seu negócio em todos os setores.
                            </div>

                            <div className="item-accordion w-100 d-flex justify-content-end">
                                <a href="#" className="btn btn-warning"> Saiba Mais!</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </main>
        </>

    );
}

export default Index;