import React from 'react';
import Head from "next/head";
import CardDepoimentos from "@/components/cards/CardDepoimentos";

function Index(props) {
    return (<>
        <Head>
            <title>SGME - Planos</title>
            <meta name="description" content="Generated by create next app"/>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
        <main className="container-fluid">
            <div className="container">
                <h1 className="text-center">Gerencie seu negócio</h1>
                <h1 className="text-center">com o <span className="paleta_Azul fw-bold">melhor investimento</span>
                </h1>
                <p className="text-center fs-3">Começe agora mesmo!</p>

                <div className="container d-sm-flex justify-content-between">
                    <div className="card col-sm-4 p-5 me-3 mb-5">
                        <h1 className="paleta_Azul">Plano de Gratis</h1>
                        <h2 className="text-center"><sup>R$</sup> 0,00 /<sub>Mensal</sub></h2>
                        <button className="btn btn-warning">Assinar</button>
                        <ul className="w-100 d-flex flex-column">
                            <li>Controle de estoque</li>
                            <li>Gestão Financeira</li>
                            <li>Controle de Vendas</li>
                            <li>Controle de Clientes</li>
                            <li>Controle de contas a pagar</li>
                            <li>Controle de contas a Receber</li>
                            <li>Blog</li>
                        </ul>
                    </div>

                    <div className="card col-sm-4 p-5 me-3 mb-5">
                        <h1 className="paleta_Azul text-center">Plano Pro</h1>
                        <h2 className="text-center"><sup>R$</sup> 14,90 /<sub>Mensal</sub></h2>
                        <button className="btn btn-warning">Assinar</button>
                        <ul>
                            <li>Controle de estoque</li>
                            <li>Gestão Financeira</li>
                            <li>Controle de Vendas</li>
                            <li>Controle de Clientes</li>
                            <li>Controle de contas a pagar</li>
                            <li>Controle de contas a Receber</li>
                            <li>Blog</li>
                            <li>Suporte a serviços dos parceiros</li>

                        </ul>
                    </div>

                    <div className="card col-sm-4 p-5 me-3 mb-5">
                        <h1 className="paleta_Azul">Plano Premium</h1>
                        <h2 className="text-center"><sup>R$</sup> 19,90 /<sub>Mensal</sub></h2>
                        <button className="btn btn-warning">Assinar</button>
                        <ul>
                            <li>Controle de estoque</li>
                            <li>Gestão Financeira</li>
                            <li>Controle de Vendas</li>
                            <li>Controle de Clientes</li>
                            <li>Controle de contas a pagar</li>
                            <li>Controle de contas a Receber</li>
                            <li>Blog</li>
                            <li>Suporte a serviços dos parceiros</li>
                            <li>Suporte a online</li>
                            <li>Tornar-se parceiro</li>
                        </ul>
                    </div>
                </div>
            </div>

            <div className="container-fluid bg-body-tertiary mt-5 mb-5">
                <div className="container-sm p-5">
                    <h1 className="text-center">Já ajudamos varios <span
                        className="text-success">empreendedores</span></h1>
                    <h1 className="text-center mb-5">a dar um <span className="text-warning">up</span> nos seus negócios
                    </h1>

                    <div className="d-flex flex-wrap justify-content-between">
                        <CardDepoimentos
                            depoimento="Eu era autônomo, com uma boa carteira de clientes, mas nunca soube administrar.
                            Com a ajuda do SGME, hoje sou um microempreendedor, a caminho do sucesso."
                            usuario="Paulo"
                        />

                        <CardDepoimentos
                            depoimento="Eu era autônomo, com uma boa carteira de clientes, mas nunca soube administrar.
                            Com a ajuda do SGME, hoje sou um microempreendedor, a caminho do sucesso."
                            usuario="Paulo"
                        />

                        <CardDepoimentos
                            depoimento="Eu era autônomo, com uma boa carteira de clientes, mas nunca soube administrar.
                            Com a ajuda do SGME, hoje sou um microempreendedor, a caminho do sucesso."
                            usuario="Paulo"
                        />
                    </div>

                </div>

            </div>

        </main>
    </>);
}

export default Index;