import {useRouter} from "next/router";
import React, {useEffect, useState} from "react";
import axios from "axios";
import Head from "next/head";
import {http} from "@/utils/http";
import ModalComponent from "@/components/ModalComponent";
import ButtonFechar from "@/components/ButtonFechar";
import {getUserFromCookie} from "@/utils/Cookies";
import InputMask from "react-input-mask";

const UpdateCliente = () => {

    const [modalIsOpen, setModalIsOpen] = useState(false);

    const openModal = () => {
        setModalIsOpen(true);
    };

    const closeModal = () => {
        setModalIsOpen(false);
        router.push('/gestao-sgme/clientes')
    };


    const router = useRouter();


    const [errorApi, setErroApi] = useState()
    const [resultErro, setResultErro] = useState(false)
    const [status, setStatus] = useState([false])


    const [cliente, setCliente] = useState(
        {
            id: 0,
            cpf: "",
            nome: "",
            telefone: "",
            data_nascimento: ""
        }
    );

    const {codigo} = router.query;
    useEffect(() => {

        const dataUser = getUserFromCookie();

        if (codigo) {
            http.get(`/clientes/${codigo}`, {
                headers: {
                    Authorization: `Bearer ${dataUser.token}`
                }
            })
                .then((response) => {
                    setCliente(response.data)
                })
                .catch((response) => {
                    console.error('Erro atualizar busca na pagina!')
                })
        }

    }, [codigo])


    const handleUpdateCliente = async () => {
        const dataUser = getUserFromCookie();

        await http.put(`/clientes/${codigo}`, cliente, {
            headers: {
                Authorization: `Bearer ${dataUser.token}`
            }
        })
            .then((response) => {
                setResultErro(false)
                abrirModal()
            })
            .catch((error) => {
                if (axios.isAxiosError(error)) {
                    setResultErro(true)
                    setErroApi(error.response.data.message)
                }
            });

    }

    const abrirModal = (erroApi) => {
        setStatus(true)
        openModal()
    }

    console.log(errorApi)
    const handleInputChange = (e) => {
        setCliente({...cliente, [e.target.name]: e.target.value});
    };

    const handlerCancelar = () => {
        router.push("/gestao-sgme/clientes");
    }

    return (
        <>
            <Head>
                <title>SGME - Alterando Clientes</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>

            </Head>
            <div className="container-sm d-flex align-items-center justify-content-start mt-5">

                <form className="form-control-sm w-100" style={{maxWidth:"75%"}}>

                    <h3 className="mb-4">Atualizando Clientes</h3>
                    <div className="d-sm-flex flex-column">
                        <label htmlFor="valor">Nome Completo: </label>
                        <input placeholder="Nome"
                               className="form-control"
                               name="nome"
                               value={cliente.nome}
                               onChange={handleInputChange}
                        />
                    </div>

                    <div className="d-sm-flex flex-row justify-content-between mb-3">
                        <div className="d-sm-flex flex-column w-100 me-3">
                            <label htmlFor="valor">CPF: </label>
                            <InputMask
                                mask="999.999.999-99"
                                maskChar="_"
                                placeholder="Cpf"
                                className="form-control"
                                name="cpf"
                                value={cliente.cpf}
                                onChange={handleInputChange}
                            />
                            {resultErro === true ? (
                                <p className="text-danger fw-bold">{errorApi}</p>
                            ) : ("")}
                        </div>


                        <div className="d-sm-flex flex-column w-100  me-3">
                            <label htmlFor="data_vencimento">Data Nascimento: </label>
                            <input type="date"
                                   className="form-control"
                                   name="data_nascimento"
                                   value={cliente.data_nascimento}
                                   onChange={handleInputChange}
                            />

                        </div>
                        <div className="d-sm-flex flex-column w-100 ">
                            <label htmlFor="data_vencimento">Telefone</label>
                            <InputMask
                                mask="(99) 99999-9999"
                                maskChar="_"
                                   placeholder="Telefone/Celular"
                                   className="form-control"
                                   name="telefone"
                                   value={cliente.telefone}
                                   onChange={handleInputChange}
                            />

                        </div>

                    </div>

                    <div className="d-flex">
                        <button className="btn btn-success pe-3 ps-3 me-3" onClick={(e) => {
                            e.preventDefault();
                            const promise = handleUpdateCliente();
                            // openModal()
                        }}>SALVAR
                        </button>
                        <button className="btn btn-danger pe-3 ps-3" onClick={(e) => {
                            e.preventDefault();
                            handlerCancelar();

                        }}>CANCELAR
                        </button>
                    </div>


                    <ModalComponent
                        isOpen={modalIsOpen}
                        onRequestClose={closeModal}
                    >
                        {status === true ? (
                            <div>
                                <p className="fw-bold text-success">Cliente alterado com sucesso</p>
                            </div>

                        ) : (
                            <>
                                <p>Erro ao atualizar</p>
                                <p>{errorApi}</p>

                            </>

                        )}


                    </ModalComponent>


                </form>


            </div>


        </>
    )
}

export default UpdateCliente;