import React from 'react';
import CardSiteFuncoes from '/components/cards/CardSiteFuncoes'
import Link from "next/link";
import Image from "next/image";
import CardSiteBlog from "@/components/cards/CardSiteBlog";
import CardDepoimentos from "@/components/cards/CardDepoimentos";
import Head from "next/head";

function Index(props) {
    return (
        <>
            <Head>
                <title>SGME - Home</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className="container-sm">

                <div className="container-sm d-sm-flex justify-content-between mb-5">

                    <div className="container-sm d-sm-flex flex-column justify-content-between p-5">
                        <div>
                            <h1>UM SISTEMA PENSADO PARA O MICROEMPREENDEDOR</h1>
                        </div>

                        <div>
                            <p className="fs-5">
                                O sistema perfeito para auxiliar micro e pequenos empresários,
                                no gerenciamento do seu negócio. Controle de
                                fluxo financeiro, Gestão de Estoque e uma base de conhecimento
                                para ajudar a gerir seu négocio.
                            </p>
                            <p className="fs-4">Tudo isso na Palma da mão!</p>
                        </div>

                        <Link
                            href="/cadastro"
                            className="btn btn-warning pt-3 pb-3 w-100"
                        >
                            Crie Sua Conta Grátis
                        </Link>
                    </div>


                        <div>
                            <Image src="/img/icone_banner_home.svg" width={400} height={400} alt=""/>
                        </div>



                </div>

                <h1 className="text-center "><span style={{color: "#4682B4"}}>Conheça</span> tudo o que oferecemos</h1>


                <div className="container d-sm-flex flex-wrap justify-content-between w-100 mb-3 ">
                    <CardSiteFuncoes
                        img="/img/icone_func_cadastros.svg"
                        title="Cadastros"
                        info="Produtos, Fornecedores, Clientes, Vendedores, Categorias"
                        link="#"

                    />
                    <CardSiteFuncoes
                        img="/img/icone_func_financeiro.svg"
                        title="Gestão Financeira"
                        info="Controle de Caixa, Contas a Pagar e Contas a Receber"
                        link="#"
                    />

                    <CardSiteFuncoes
                        img="/img/icone_func_conhecimento.svg"
                        title="Blog da SGME"
                        info="Cursos e formações com ONGs parceiras para ajudar na gestão do seu negócio."
                        link="#"
                    />

                    <CardSiteFuncoes
                        img="/img/icone_func_pdv.svg"
                        title="PDV - Ponto de Venda"
                        info="Controle de Caixa, Contas a Pagar e Contas a Receber"
                        link="#"
                    />

                    <CardSiteFuncoes
                        img="/img/icone_func_estoque.svg"
                        title="Gestão de Estoque"
                        info="Seu estoque sempre atualizado, contabilizando entradas e saídas de mercadorias."
                        link="#"
                    />

                    <CardSiteFuncoes
                        img="/img/icone_func_relatorios.svg"
                        title="Relatórios"
                        info="Vendas, Contas a Pagar e Receber, Estoque Atual, Estoque Negativo Fluxo de Caixa."
                        link="#"
                    />


                </div>

                <h1 className="text-center mb-5 mt-5"><span style={{color: "#FF5510"}} className="mt-5">Explore</span> nossa
                    base de conhecimentos</h1>

                <div className="container d-sm-flex flex-wrap justify-content-between w-100 mb-3">
                    <CardSiteBlog
                        img="/img/Parceiros.jpg"
                        title="Tudo sobre MEI"
                        info="O passo a passo de como abrir um MEI e obter um CNPJ é fácil, mas exige responsabilidades como
                     pagar guia DAS MEI, declarações anuais e emitir notas fiscais para outro CNPJ."
                        fonte="Sebrae"
                        link="#"/>

                    <CardSiteBlog
                        img="/img/Parceiros.jpg"
                        title="Tudo sobre MEI"
                        info="O passo a passo de como abrir um MEI e obter um CNPJ é fácil, mas exige responsabilidades como
                     pagar guia DAS MEI, declarações anuais e emitir notas fiscais para outro CNPJ."
                        fonte="Sebrae"
                        link="#"/>

                    <CardSiteBlog
                        img="/img/Parceiros.jpg"
                        title="Tudo sobre MEI"
                        info="O passo a passo de como abrir um MEI e obter um CNPJ é fácil, mas exige responsabilidades como
                     pagar guia DAS MEI, declarações anuais e emitir notas fiscais para outro CNPJ."
                        fonte="Sebrae"
                        link="#"/>

                    <CardSiteBlog
                        img="/img/Parceiros.jpg"
                        title="Tudo sobre MEI"
                        info="O passo a passo de como abrir um MEI e obter um CNPJ é fácil, mas exige responsabilidades como
                     pagar guia DAS MEI, declarações anuais e emitir notas fiscais para outro CNPJ."
                        fonte="Sebrae"
                        link="#"/>

                </div>

                <h1 className="tip-before text-center mb-5 text-danger"> Depoimentos</h1>

                <div className="d-flex flex-wrap justify-content-between">
                    <CardDepoimentos
                        depoimento="Eu era autônomo, com uma boa carteira de clientes, mas nunca soube administrar.
                Com a ajuda do SGME, hoje sou um microempreendedor, a caminho do sucesso."
                        usuario="Paulo"
                    />

                    <CardDepoimentos
                        depoimento="Eu era autônomo, com uma boa carteira de clientes, mas nunca soube administrar.
                Com a ajuda do SGME, hoje sou um microempreendedor, a caminho do sucesso."
                        usuario="Paulo"
                    />

                    <CardDepoimentos
                        depoimento="Eu era autônomo, com uma boa carteira de clientes, mas nunca soube administrar.
                Com a ajuda do SGME, hoje sou um microempreendedor, a caminho do sucesso."
                        usuario="Paulo"
                    />

                </div>

            </main>
        </>

    );
}

export default Index;