import React from 'react';
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

function Index(props) {
    return (
        <>
            <Head>
                <title>SGME - Funcionalidades</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>

            </Head>
            <main className="container">

                <section className="container-sm">
                    <div
                        className="flex-md-row-reverse w-100 d-lg-flex justify-content-between align-items-center"
                    >
                        <div className="d-flex justify-content-end">
                            <Image src="/img/icone_parceria.svg" width={400} height={400} alt=""/>
                        </div>

                        <div >
                            <h1 className="mb-5">
                                Mais que parceiros, somos criadores de oportunidades de negócio!
                            </h1>
                            <p className="fs-5">
                                Acreditamos em <strong className="text-info">Parcerias</strong> onde
                                grandes <strong className="text-info">oportunidades</strong> são
                                geradas por meio de ideias que se conectam. Conheça nossas
                                parcerias e escolha a melhor para o seu negócio!
                            </p>
                        </div>
                    </div>
                </section>

                <section className="container mb-5">
                    <div className="w-100 d-sm-flex align-items-center">

                        <div className="d-lg-flex align-items-center">
                            <Image
                                src="/img/icone_parceira_motivo.svg"
                                width={400}
                                height={400}
                                alt=""
                            />
                        </div>

                        <div>
                            <h1 className="mb-5 text-paleta_laranja">
                                Por que ser um parceiro da SGME?
                            </h1>
                            <p>
                                O programa de parcerias da SGME oferece oportunidades únicas para você gerar mais valor
                                ao seu negócio!
                            </p>
                            <p>
                                Juntos podemos mudar vidas, impulsionando e divulgando o seu negócio aqui na nossa
                                plataforma. Somos uma solução que foca em ajudar microempreendedores a crescer e
                                buscamos parceiros que possa nos ajudar a alcançar esse objetivo
                            </p>
                            <p>
                                Vamos juntos crescer e mudar vidas. Se torne um parceiro!
                            </p>

                            <Link href="#" className="btn btn-warning">
                                Clique aqui e seja um parceiro</Link
                            >
                        </div>
                    </div>
                </section>

                <section className="container">
                    <h1 className="text-center mt-5 mb-5">
                        Conheça nossos <span className="text-paleta_laranja">modelos de parcerias</span>
                    </h1>

                    <div className="parcerias">
                        <div className="container w-100 d-lg-flex  flex-md-row-reverse">

                            <div>
                                <Image
                                    src="/img/ongs_tipo_parceria.svg"
                                    width={350}
                                    height={350}
                                    alt=""
                                />
                            </div>

                            <div className="parceiro-card_content ">
                                <h1 className="mb-5 text-paleta_laranja">Parcerias com ONGs</h1>
                                <p>
                                    Se você é uma ONG que busca ajudar mentes empreendedoras e ainda não tem um sistema
                                    de gestão para esse microempreendedor, aqui oferemos uma solução simples e
                                    intuitiva, fácil de usar, que o ajudará a alcançar o seu objetivo! Ajudamos você a
                                    mudar vidas atraves de uma gestão simples e de fácil usabilidade.
                                </p>
                                <p>
                                    Como ONG, você leva as pessoas a solução para gestão do seu negócio a pessoas que
                                    estao começando a empreender e aqui na plataforma, você tem um parceiro para ajudar
                                    a alcançar esse objetivo!
                                </p>
                                <p>
                                    Vamos juntos mudar vidas e transformar a gestão de negócio dos microempreendedores.
                                </p>

                                <Link href="#" className="btn btn-warning">
                                    Clique aqui e seja um parceiro</Link
                                >
                            </div>


                        </div>
                    </div>

                    <div className="parcerias mb-3">
                        <div className=" w-100 d-sm-flex align-items-center">
                            <div className="w-100">
                                <Image
                                    src="/img/Icone_prestadora_serviços.svg"
                                    width={350}
                                    height={350}
                                    alt=""
                                />
                            </div>

                            <div>
                                <h1 className="mb-5 text-paleta_laranja">
                                    Empresas Prestadoras de Serviço Para MEI
                                </h1>
                                <p>
                                    Aqui, você tem espaço para oferecer seu serviço aos nossos clientes. Lembrando que,
                                    nosso objetivo é ajudar e incentivar o crescimento dos microempreendedoes. Então, se
                                    o seu serviço tem como objetivo alcançar essas pessoas, vamos juntos.
                                </p>
                                <p>
                                    Você possui uma solução complementar ao nosso sistema através de parcerias voltadas
                                    à expansão de marca? Nós queremos te ouvir!
                                </p>
                                <p>
                                    Aqui você pode sugerir parcerias relacionadas a conteúdos voltados para
                                    microempreendedoes, serviços que visam incentivar o crescimento do negócio desse
                                    microempreendedor, entre outras.
                                </p>

                                <Link href="#" className="btn btn-warning">
                                    Clique aqui e seja um parceiro</Link
                                >
                            </div>
                        </div>
                    </div>
                </section>

            </main>
        </>
    );
}

export default Index;