import React from 'react';
import Head from "next/head";
import CardSiteBlog from "@/components/cards/CardSiteBlog";

function Index(props) {
    return (
        <>
            <Head>
                <title>SGME - Blog</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className="container-sm">
                <div className="banner container-fluid mt-5 mb-5 ">
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img src="/img/banner_blog.jpg" className="w-100" alt="Banner page base de conhecimento"/>
                </div>

                <div className="pesquisa container">
                    <form className="d-flex  m-3" role="search">
                        <input className="form-control me-2" type="search" placeholder="Pesquisa" aria-label="Search"/>
                        <button className="btn btn-warning ps-5 pe-5" type="submit">Buscar</button>
                    </form>
                </div>

                <h1 className="text-center">
                    <span className="text-paleta_laranja">Explore</span> nossa base de
                    conhecimento.
                </h1>

                <div className="container d-sm-flex flex-wrap justify-content-between w-100 mb-3">
                    <CardSiteBlog
                        img="/img/Parceiros.jpg"
                        title="Tudo sobre MEI"
                        info="O passo a passo de como abrir um MEI e obter um CNPJ é fácil, mas exige responsabilidades como pagar
                    guia DAS MEI, declarações anuais e emitir notas fiscais para outro CNPJ."
                        link="#"
                        fonte="Sebraae"
                    />
                    <CardSiteBlog
                        img="/img/Parceiros.jpg"
                        title="Tudo sobre MEI"
                        info="O passo a passo de como abrir um MEI e obter um CNPJ é fácil, mas exige responsabilidades como pagar
                        guia DAS MEI, declarações anuais e emitir notas fiscais para outro CNPJ."
                        link="#"
                        fonte="Sebraae"
                    />

                    <CardSiteBlog
                        img="/img/Parceiros.jpg"
                        title="Tudo sobre MEI"
                        info="O passo a passo de como abrir um MEI e obter um CNPJ é fácil, mas exige responsabilidades como pagar
                        guia DAS MEI, declarações anuais e emitir notas fiscais para outro CNPJ."
                        link="#"
                        fonte="Sebraae"
                    />

                    <CardSiteBlog
                        img="/img/Parceiros.jpg"
                        title="Tudo sobre MEI"
                        info="O passo a passo de como abrir um MEI e obter um CNPJ é fácil, mas exige responsabilidades como pagar
                        guia DAS MEI, declarações anuais e emitir notas fiscais para outro CNPJ."
                        link="#"
                        fonte="Sebraae"
                    />
                    
                </div>

            </main>
        </>
    );
}

export default Index;