import React, {useEffect, useState} from 'react';
import Link from "next/link";
import Head from "next/head";
import {getReceitasData} from "@/utils/getReceitas";
import {format, parseISO} from "date-fns";
import {ptBR} from "date-fns/locale";

function Index() {
    const [receitas, setReceitas] = useState([]);

    useEffect(() => {
        const getData = async () => {
            try {
                const receitasData = await getReceitasData();
                setReceitas(receitasData);
            } catch (error) {
                console.error("Erro ao buscar dados", error);
            }
        };


        getData();
    }, []);



    return (
        <>
            <Head>
                <title>SGME - Lista de contas a receber</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>

            </Head>
            <main className="container">
                <div className="container d-sm-flex flex-row justify-content-between mb-3">
                    <h3>Contas a Receber</h3>
                    <Link href="/gestao-sgme/financeiro/contas-a-receber/cadastro" className="btn btn-success">Novo
                        Receita</Link>
                </div>

                <div className="overflow-x-scroll">
                    <table className="table">
                        <thead>
                        <tr className="border border-2 border-warning">
                            <th scope="col">Cliente</th>
                            <th scope="col">Valor</th>
                            <th scope="col">Vencimento</th>
                            <th scope="col">Status</th>
                            <th scope="col" className=" d-flex justify-content-end">Ações</th>

                        </tr>
                        </thead>
                        <tbody>

                        {receitas && receitas.length > 0 ? (
                            receitas.map(receita => (
                                <tr key={receita.id}>
                                    <td>{receita.nomeCliente}</td>
                                    <td>R$ {receita.valor.toFixed(2)}</td>
                                    <td>{format(parseISO(receita.data_vencimento), 'dd/MM/yyyy', {locale: ptBR})}</td>
                                    <td>{receita.status}</td>
                                    <td className="d-flex justify-content-end">
                                        <Link href={`/gestao-sgme/financeiro/contas-a-receber/update/${receita.id}`}
                                              className="btn btn-success me-2">EDITAR</Link>
                                        <Link href={`/gestao-sgme/financeiro/contas-a-receber/delete/${receita.id}`}
                                              className="btn btn-danger">EXCLUIR</Link>
                                    </td>
                                </tr>
                            ))
                        ) : (
                            <tr>
                                <td colSpan="6">Nenhuma despesa encontrada.</td>
                            </tr>
                        )}

                        </tbody>
                    </table>
                </div>


            </main>
        </>

    );
}

export default Index;